import SectionWrapper from "./sectionWrapper";

export { SectionWrapper };

// HOC -  higher order component

// generated by chatGPT for better understanding

// Importing and exporting the same component in index.js allows for a more convenient way to access the component when importing it in other files.

// In this specific case, index.js serves as a central export file for the higher-order components (HOCs) in the hoc directory. By exporting SectionWrapper from index.js, it becomes the default export of the hoc module.

// When using the SectionWrapper component in other files, developers can simply import it from the hoc directory without having to specify the exact file name. This can be beneficial when there are multiple HOCs within the hoc directory, as it provides a cleaner and more organized way to import them.
